name: EAS Build & Submit to Google Playstore (Android)
on:
  push:
    branches:
      - '**'
    paths:
      - app/app.json
defaults:
  run:
    working-directory: app
jobs:
  update:
    name: EAS Build & Submit to Google Playstore (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: ./app/yarn.lock

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: EAS Build & Submit to Google Playstore (Android)
        run: eas build -p android -e development --auto-submit
        timeout-minutes: 3 # Set your desired timeout in minutes here