name: EAS Update Production Apps
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "app/**"
      - "!app/e2e/**"
      - "!app/eas-hooks/**"

defaults:
  run:
    working-directory: app
jobs:
  update:
    name: EAS Update Production Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: ./app/yarn.lock

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn testFinal

      - name: EAS Update Production Apps (Production)
        if: github.ref == 'refs/heads/main'
        run: NODE_ENV=production eas update --branch production --auto # Closed testing track (Alpha)

      - name: EAS Update Production Apps (Development)
        if: github.ref == 'refs/heads/develop'
        run: NODE_ENV=development eas update --branch development --auto # Internal track
