name: Deploy Firebase Functions
on:
  push:
    branches:
      - '**'
    paths:
      - server/functions/**
defaults:
  run:
    working-directory: server/functions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: ./server/functions/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firebase function
        run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}