name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
      - develop
    paths:
      - web/**
      - web/src/**
      - ".github/workflows/web_deploy.yml"
defaults:
  run:
    working-directory: web

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies & build (Development)
        if: github.ref == 'refs/heads/develop'
        run: npm ci && REACT_APP_NODE_ENV=development npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase (Development)
        if: github.ref == 'refs/heads/develop'
        run: firebase use makeshiftplans-dev && firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Install dependencies & build (Production)
        if: github.ref == 'refs/heads/main'
        run: npm ci && REACT_APP_NODE_ENV=production npm run build

      - name: Deploy to Firebase (Production)
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAKESHIFTPLANS_PROD }}"
          projectId: makeshiftplans-prod
          entryPoint: web
          channelId: live

      # - name: Deploy to Firebase (Development)
      #   if: github.ref == 'refs/heads/develop'
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAKESHIFTPLANS_DEV }}"
      #     projectId: makeshiftplans-dev
      #     entryPoint: web
      #     channelId: live
