name: EAS Build & Submit to Google Playstore (Android)
on:
  push:
    branches:
      - main
      - develop
    paths:
      - app/abc # prevent runs
      # - app/app.config.js
defaults:
  run:
    working-directory: app
jobs:
  update:
    name: EAS Build & Submit to Google Playstore (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          cache-dependency-path: ./app/yarn.lock

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn testFinal

      - name: Decode Google Play Service Account
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" | base64 --decode > pc-api-6795295579632533760-300-d0f297d14ac0.json

      - name: EAS Build & Submit to Google Playstore (Android) (Production)
        if: github.ref == 'refs/heads/main'
        run: NODE_ENV=production eas build -p android -e production --auto-submit --non-interactive --no-wait

      - name: EAS Build & Submit to Google Playstore (Android) (Development)
        if: github.ref == 'refs/heads/develop'
        run: NODE_ENV=development eas build -p android -e development --auto-submit --non-interactive --no-wait
